version : '3'
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_shipments_test
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  database-data:
    driver: local